(setq my-ostype 'openbsd) ; windows mac linux
(setq use-ecb t)
(setq use-lambda nil)
(setq use-twitter nil)
(setq my-workspace-dir "~/workspace/")
(setq my-ecb-layout "lefttim3")
(setq sql-user "root")
(setq sql-password "put-password-here")
(setq sql-database "mysql")
(setq sql-server "localhost")
(setq twittering-username "your-twitter-username")
(setq twittering-password "your-twitter-pass")
