; yegge custom key bindings
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\M-z" 'backward-kill-word)
(global-set-key "\C-w" 'kill-region)
; following is useful if above is bound to C-w
; (global-set-key "\C-x\C-k" 'kill-region)
; (global-set-key "\C-c\C-k" 'kill-region)
(global-set-key "\C-co" 'copy-region-as-kill)
(global-set-key "\C-c\C-l" 'whole-line-region)
(global-set-key "\M-r" 'isearch-backward-regexp)
(global-set-key "\M-s" 'isearch-forward-regexp)
(global-set-key "\M-p" 'fill-paragraph)
(global-set-key "\C-c\C-r" 'compile)
(global-set-key "\C-x\C-am" 'add-mode-abbrev)
(defalias 'qrr 'query-replace-regexp)
(defalias 'qr 'query-replace)
(defalias 'sb 'swap-buffers)
(defalias 'cmp 'compile)
(defalias 'rb 'revert-buffer)
(defalias 'df 'delete-frame)
(defalias 'mate 'open-in-textmate)
(defalias 'mated 'open-dir-in-textmate)
(defalias 'ts 'my-toggle-fullscreen)
(defalias 'ew 'emacswiki)
(global-set-key "\C-c\C-d" 'ecb-deactivate)
(global-set-key "\C-c\C-e" 'ecb-activate)

(global-set-key [f5] 'call-last-kbd-macro)
(global-set-key [f6] 'compile)
