;(load-library "wc")
;(load-library "window-number")
(load-library "dired-details")
;(require 'dired-details)
(dired-details-install)
;(load-library "countchars.el")
;(load-library "google")
;(load-library "fullscreen")
(load-library "browse-kill-ring")
(load-library "edit-server")
(load-library "shut-up")
(load-library "editorconfig")
